/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Ventanas;

import Clases.CustomEditor8;
import Clases.PareoCodigo;
import DAO.IngresosDAO;
import DAO.PareoCodigoDAO;
import DAO.ProductoOrdenDeCompraDAO;
import Logica.LogicaPrincipal;
import static Logica.LogicaPrincipal.vd;
import static Ventanas.VentanaDetalle.arrPoductoOrdenDeCompra;
import static Ventanas.VentanaDetalle.arrProductosIngresados;
import static Ventanas.VentanaMain.numeroOC;
import static Ventanas.VentanaMain.proveedor;
import com.tagmycode.plugin.gui.TextPrompt;
import java.awt.Font;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sopor
 */
public class VentanaAgregarCodigo1 extends javax.swing.JDialog {

    String codigoOriginal;

    /**
     * Creates new form VentanaAgregarCodigo1
     */
    public VentanaAgregarCodigo1(java.awt.Frame parent, boolean modal, String codigoOriginal) {
        super(parent, modal);
        initComponents();
        this.codigoOriginal = codigoOriginal;

        TextPrompt placeholder = new TextPrompt("Codigo", jTextField1);
        placeholder.changeAlpha(0.75f);
        placeholder.changeStyle(Font.ITALIC);

        placeholder = new TextPrompt("RTU", jTextField2);
        placeholder.changeAlpha(0.75f);
        placeholder.changeStyle(Font.ITALIC);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        jButton1.setText("AGREGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*", "/", "+", "-" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:       
        if (!jTextField1.getText().trim().equals("") || jTextField2.getText().trim().equals("")) {
            PareoCodigo pareoCodigo = new PareoCodigo();
            pareoCodigo.setCodigoOriginal(codigoOriginal);
            pareoCodigo.setCodigo1(jTextField1.getText().trim());
            pareoCodigo.setRtu1(jTextField2.getText().trim());
            pareoCodigo.setOperador1(jComboBox1.getSelectedItem().toString());
            pareoCodigo.setProveedor(VentanaMain.proveedor);
            PareoCodigoDAO.insertPareoCodigoCodigo1(pareoCodigo);

            dispose();
            vd.dispose();

            vd = new VentanaDetalle(VentanaMain.ventanaPrincipal, true);
            vd.setLocationRelativeTo(VentanaMain.ventanaPrincipal);

            VentanaDetalle.jLabel2.setText(numeroOC);
            VentanaDetalle.jLabel4.setText(proveedor);

            try {
                arrPoductoOrdenDeCompra = ProductoOrdenDeCompraDAO.selectproductoOrdenDeCompraWhere(numeroOC, proveedor);
                arrProductosIngresados = IngresosDAO.selectProductoIngresado(numeroOC);
            } catch (SQLException ex) {
                Logger.getLogger(CustomEditor8.class.getName()).log(Level.SEVERE, null, ex);
            }

            System.out.println("arrProductosIngresados.size() " + arrProductosIngresados.size());
            LogicaPrincipal.cargaTablaDetalle();

            vd.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(VentanaMain.ventanaPrincipal, "Debe Ingresar un Codigo", "¿?", JOptionPane.ERROR_MESSAGE);
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
